# Generated by Django 5.0.7 on 2024-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_format', models.CharField(max_length=255)),
                ('id_value', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('client_group_id', models.IntegerField()),
                ('primary_account_id', models.IntegerField(blank=True, null=True)),
                ('primary_account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('id_code', models.CharField(max_length=255)),
                ('contact_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
        ),
    ]
