# Generated by Django 5.0.7 on 2024-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_format', models.CharField(max_length=255)),
                ('id_value', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('client_group_id', models.IntegerField()),
                ('primary_account_id', models.IntegerField(blank=True, null=True)),
                ('primary_account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('id_code', models.CharField(max_length=255)),
                ('contact_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='packageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('html', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='packageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_format', models.CharField(max_length=255)),
                ('id_value', models.CharField(max_length=255)),
                ('id_code', models.CharField(max_length=255)),
                ('module_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('client_qty', models.IntegerField(blank=True, null=True)),
                ('module_row', models.IntegerField()),
                ('module_group', models.IntegerField(blank=True, null=True)),
                ('module_group_client', models.IntegerField()),
                ('taxable', models.BooleanField()),
                ('single_term', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('hidden', models.BooleanField()),
                ('company_id', models.IntegerField()),
                ('prorata_day', models.IntegerField(blank=True, null=True)),
                ('prorata_cutoff', models.IntegerField(blank=True, null=True)),
                ('upgrades_use_renewal', models.BooleanField()),
                ('manual_activation', models.BooleanField()),
                ('override_price', models.BooleanField()),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('descriptions', models.ManyToManyField(related_name='packages', to='blare.packagedescription')),
                ('names', models.ManyToManyField(related_name='packages', to='blare.packagename')),
            ],
        ),
    ]
