# Generated by Django 5.0.7 on 2024-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='module_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
