# Generated by Django 5.0.7 on 2024-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blare', '0002_alter_package_module_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
