# Generated by Django 5.0.7 on 2024-07-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='mailing_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
